// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyCDj4IJELpJqQeT2A6uWhlR7Z8jgVnNvp8',
      appId: '1:1032062349714:android:d52e636e6b0e8ba19b514b',
      messagingSenderId: '1032062349714',
      projectId: 'sentiments-anaylsis',
      authDomain: 'sentiments-anaylsis.web.app');

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzrk8jP8MmfcyIpS8NM4lF8ItZgAAXkto',
    appId: '1:670634970719:android:a8ba0c6f705565f90d55ea',
    messagingSenderId: '670634970719',
    projectId: 'em2-2024',
    storageBucket: 'em2-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1BHTKZqHIKL1nZyxCPAryeEzkEZdAUzk',
    appId: '1:670634970719:ios:b719d1f368ae6b560d55ea',
    messagingSenderId: '670634970719',
    projectId: 'em2-2024',
    storageBucket: 'em2-2024.appspot.com',
    androidClientId:
        '670634970719-sgm0r86mj5nlf1l6ug27thc0l9rjqmsn.apps.googleusercontent.com',
    iosClientId:
        '670634970719-itl28fl6is38fojbhs4ml5qcehpgn5dl.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1BHTKZqHIKL1nZyxCPAryeEzkEZdAUzk',
    appId: '1:670634970719:ios:e42387b4a3eaefe40d55ea',
    messagingSenderId: '670634970719',
    projectId: 'em2-2024',
    storageBucket: 'em2-2024.appspot.com',
    androidClientId:
        '670634970719-sgm0r86mj5nlf1l6ug27thc0l9rjqmsn.apps.googleusercontent.com',
    iosClientId:
        '670634970719-8454bpc4f3sjvfduk4rjahg6pqr3hnpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorAdmin.RunnerTests',
  );
}
